SCORECARD_POINTS = 0;
 
*------------------------------------------------------------*;
* Variable: ACTIVE;
*------------------------------------------------------------*;
if MISSING(ACTIVE) then do;
SCORECARD_POINTS = SCORECARD_POINTS + 29;
SCR_ACTIVE= 29;
end;
else if NOT MISSING(ACTIVE) AND ACTIVE < 2 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 125;
SCR_ACTIVE = 125;
end;
else if NOT MISSING(ACTIVE) and 2 <= ACTIVE AND ACTIVE < 12 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 29;
SCR_ACTIVE = 29;
end;
else if NOT MISSING(ACTIVE) and 12 <= ACTIVE AND ACTIVE < 16 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 4;
SCR_ACTIVE = 4;
end;
else if NOT MISSING(ACTIVE) and 16 <= ACTIVE AND ACTIVE < 19 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 22;
SCR_ACTIVE = 22;
end;
else if NOT MISSING(ACTIVE) and 19 <= ACTIVE then do;
SCORECARD_POINTS = SCORECARD_POINTS + 3;
SCR_ACTIVE = 3;
end;
 
*------------------------------------------------------------*;
* Variable: AGE;
*------------------------------------------------------------*;
if MISSING(AGE) then do;
SCORECARD_POINTS = SCORECARD_POINTS + 39;
SCR_AGE= 39;
end;
else if NOT MISSING(AGE) AND AGE < 27.58 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 39;
SCR_AGE = 39;
end;
else if NOT MISSING(AGE) and 27.58 <= AGE AND AGE < 32.58 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 31;
SCR_AGE = 31;
end;
else if NOT MISSING(AGE) and 32.58 <= AGE AND AGE < 37.25 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 22;
SCR_AGE = 22;
end;
else if NOT MISSING(AGE) and 37.25 <= AGE AND AGE < 52.42 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 26;
SCR_AGE = 26;
end;
else if NOT MISSING(AGE) and 52.42 <= AGE then do;
SCORECARD_POINTS = SCORECARD_POINTS + 21;
SCR_AGE = 21;
end;
 
*------------------------------------------------------------*;
* Variable: AVGEXP;
*------------------------------------------------------------*;
if MISSING(AVGEXP) then do;
SCORECARD_POINTS = SCORECARD_POINTS + 28;
SCR_AVGEXP= 28;
end;
else if NOT MISSING(AVGEXP) AND AVGEXP < 12.65 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 28;
SCR_AVGEXP = 28;
end;
else if NOT MISSING(AVGEXP) and 12.65 <= AVGEXP AND AVGEXP < 57.44 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 49;
SCR_AVGEXP = 49;
end;
else if NOT MISSING(AVGEXP) and 57.44 <= AVGEXP AND AVGEXP < 101.76 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 29;
SCR_AVGEXP = 29;
end;
else if NOT MISSING(AVGEXP) and 101.76 <= AVGEXP AND AVGEXP < 352.17 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 36;
SCR_AVGEXP = 36;
end;
else if NOT MISSING(AVGEXP) and 352.17 <= AVGEXP then do;
SCORECARD_POINTS = SCORECARD_POINTS + 15;
SCR_AVGEXP = 15;
end;
 
*------------------------------------------------------------*;
* Variable: CUR_ADD;
*------------------------------------------------------------*;
if MISSING(CUR_ADD) then do;
SCORECARD_POINTS = SCORECARD_POINTS + 40;
SCR_CUR_ADD= 40;
end;
else if NOT MISSING(CUR_ADD) AND CUR_ADD < 24 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 40;
SCR_CUR_ADD = 40;
end;
else if NOT MISSING(CUR_ADD) and 24 <= CUR_ADD AND CUR_ADD < 49 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 26;
SCR_CUR_ADD = 26;
end;
else if NOT MISSING(CUR_ADD) and 49 <= CUR_ADD AND CUR_ADD < 108 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 23;
SCR_CUR_ADD = 23;
end;
else if NOT MISSING(CUR_ADD) and 108 <= CUR_ADD AND CUR_ADD < 192 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 28;
SCR_CUR_ADD = 28;
end;
else if NOT MISSING(CUR_ADD) and 192 <= CUR_ADD then do;
SCORECARD_POINTS = SCORECARD_POINTS + 19;
SCR_CUR_ADD = 19;
end;
 
*------------------------------------------------------------*;
* Variable: INCOME;
*------------------------------------------------------------*;
if MISSING(INCOME) then do;
SCORECARD_POINTS = SCORECARD_POINTS + 31;
SCR_INCOME= 31;
end;
else if NOT MISSING(INCOME) AND INCOME < 1.8 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 41;
SCR_INCOME = 41;
end;
else if NOT MISSING(INCOME) and 1.8 <= INCOME AND INCOME < 2.06 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 27;
SCR_INCOME = 27;
end;
else if NOT MISSING(INCOME) and 2.06 <= INCOME AND INCOME < 4.8 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 31;
SCR_INCOME = 31;
end;
else if NOT MISSING(INCOME) and 4.8 <= INCOME AND INCOME < 5.48 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 43;
SCR_INCOME = 43;
end;
else if NOT MISSING(INCOME) and 5.48 <= INCOME then do;
SCORECARD_POINTS = SCORECARD_POINTS + 17;
SCR_INCOME = 17;
end;
