PROC FACTOR DATA=DISCO.BARRIOS CORR OUTSTAT=ESTEJ1F OUT=PROEJ1F COV
RESIDUALS SCORE NFACT=2 MSA PLOTS=ALL;
VAR P_TOT--TM;
RUN;

PROC FACTOR DATA=DISCO.BARRIOS CORR OUTSTAT=ESTEJ1F OUT=PROEJ1F COV
RESIDUALS SCORE NFACT=2 MSA PLOTS=ALL;
VAR P_TOT P_14 P_65 P_10 ANAL NES OCU OCUIN OCUSER TEC PD TM;
RUN;


PROC FACTOR DATA=DISCO.BARRIOS CORR OUTSTAT=ESTEJ1F OUT=PROEJ1F COV
RESIDUALS SCORE NFACT=2 MSA PLOTS=ALL;
VAR P_TOT P_14 P_65 P_10 ANAL NES OCU OCUIN TEC PD TM;
RUN;

PROC FACTOR DATA=DISCO.BARRIOS CORR OUTSTAT=ESTEJ1F OUT=PROEJ1F
RESIDUALS SCORE NFACT=2 MSA PLOTS=ALL;
VAR P_TOT P_14 P_10 ANAL NES OCU OCUIN TEC PD TM;
RUN;



proc print data=PROEJ1F;
run;

proc sgplot data=PROEJ1F;
scatter x=factor1 y=factor2 / datalabel=Barrio;
run;



PROC FACTOR DATA=DISCO.BARRIOS CORR OUTSTAT=ESTEJ1F OUT=PROEJ1F
RESIDUALS SCORE NFACT=2 MSA ROTATE=VARIMAX PLOTS=ALL;
VAR P_TOT P_14 P_10 ANAL NES OCU OCUIN TEC PD TM;
RUN;

proc print data=PROEJ1F;
run;

proc sgplot data=PROEJ1F;
scatter x=factor1 y=factor2 / datalabel=Barrio;
run;
