if name = 'SCORECARD_POINTS' then do;
role = 'ASSESS';
end;
if name = 'SCORECARD_BIN' then do;
role = 'SEGMENT';
level = 'NOMINAL';
end;
if name = 'GRP_ACTIVE' then role= 'REJECTED';
if name = 'WOE_ACTIVE' then role= 'INPUT';
if name = 'SCR_ACTIVE' then role= 'ASSESS';
if name = 'GRP_AGE' then role= 'REJECTED';
if name = 'WOE_AGE' then role= 'INPUT';
if name = 'SCR_AGE' then role= 'ASSESS';
if name = 'GRP_AVGEXP' then role= 'REJECTED';
if name = 'WOE_AVGEXP' then role= 'INPUT';
if name = 'SCR_AVGEXP' then role= 'ASSESS';
if name = 'GRP_CARDHLDR' then role= 'REJECTED';
if name = 'WOE_CARDHLDR' then role= 'INPUT';
if name = 'SCR_CARDHLDR' then role= 'ASSESS';
if name = 'GRP_CUR_ADD' then role= 'REJECTED';
if name = 'WOE_CUR_ADD' then role= 'INPUT';
if name = 'SCR_CUR_ADD' then role= 'ASSESS';
if name = 'GRP_DEPNDT' then role= 'REJECTED';
if name = 'WOE_DEPNDT' then role= 'INPUT';
if name = 'SCR_DEPNDT' then role= 'ASSESS';
if name = 'GRP_EXP_INC' then role= 'REJECTED';
if name = 'WOE_EXP_INC' then role= 'INPUT';
if name = 'SCR_EXP_INC' then role= 'ASSESS';
if name = 'GRP_INCOME' then role= 'REJECTED';
if name = 'WOE_INCOME' then role= 'INPUT';
if name = 'SCR_INCOME' then role= 'ASSESS';
if name = 'GRP_INC_PER' then role= 'REJECTED';
if name = 'WOE_INC_PER' then role= 'INPUT';
if name = 'SCR_INC_PER' then role= 'ASSESS';
if name = 'GRP_MAJOR' then role= 'REJECTED';
if name = 'WOE_MAJOR' then role= 'INPUT';
if name = 'SCR_MAJOR' then role= 'ASSESS';
if name = 'GRP_OWNRENT' then role= 'REJECTED';
if name = 'WOE_OWNRENT' then role= 'INPUT';
if name = 'SCR_OWNRENT' then role= 'ASSESS';
if name = 'GRP_SELFEMPL' then role= 'REJECTED';
if name = 'WOE_SELFEMPL' then role= 'INPUT';
if name = 'SCR_SELFEMPL' then role= 'ASSESS';
