*************************************;
*** begin scoring code for regression;
*************************************;

length _WARN_ $4;
label _WARN_ = 'Avisos' ;

length I_DEFAULT $ 10;
label I_DEFAULT = 'Into: DEFAULT' ;
*** Target Values;
array SCORECARD3DRF [2] $10 _temporary_ ('1.00' '0.00' );
label U_DEFAULT = 'Unnormalized Into: DEFAULT' ;
format U_DEFAULT COMMA10.2;
*** Unnormalized target values;
ARRAY SCORECARD3DRU[2]  _TEMPORARY_ (1 0);

*** Generate dummy variables for DEFAULT ;
drop _Y ;
label F_DEFAULT = 'From: DEFAULT' ;
length F_DEFAULT $ 10;
F_DEFAULT = put( DEFAULT , COMMA10.2 );
%DMNORMIP( F_DEFAULT )
if missing( DEFAULT ) then do;
   _Y = .;
end;
else do;
   if F_DEFAULT = '0.00'  then do;
      _Y = 1;
   end;
   else if F_DEFAULT = '1.00'  then do;
      _Y = 0;
   end;
   else do;
      _Y = .;
   end;
end;

drop _DM_BAD;
_DM_BAD=0;

*** Check WOE_AGE for missing values ;
if missing( WOE_AGE ) then do;
   substr(_warn_,1,1) = 'M';
   _DM_BAD = 1;
end;

*** Check WOE_INCOME for missing values ;
if missing( WOE_INCOME ) then do;
   substr(_warn_,1,1) = 'M';
   _DM_BAD = 1;
end;

*** Check WOE_ACTIVE for missing values ;
if missing( WOE_ACTIVE ) then do;
   substr(_warn_,1,1) = 'M';
   _DM_BAD = 1;
end;

*** Check WOE_AVGEXP for missing values ;
if missing( WOE_AVGEXP ) then do;
   substr(_warn_,1,1) = 'M';
   _DM_BAD = 1;
end;

*** Check WOE_CUR_ADD for missing values ;
if missing( WOE_CUR_ADD ) then do;
   substr(_warn_,1,1) = 'M';
   _DM_BAD = 1;
end;

*** Check WOE_DEPNDT for missing values ;
if missing( WOE_DEPNDT ) then do;
   substr(_warn_,1,1) = 'M';
   _DM_BAD = 1;
end;
*** If missing inputs, use averages;
if _DM_BAD > 0 then do;
   _P0 = 0.1055276382;
   _P1 = 0.8944723618;
   goto SCORECARD3DR1;
end;

*** Compute Linear Predictor;
drop _TEMP;
drop _LP0;
_LP0 = 0;

***  Effect: WOE_AGE ;
_TEMP = WOE_AGE ;
_LP0 = _LP0 + (   -0.91540730259371 * _TEMP);

***  Effect: WOE_INCOME ;
_TEMP = WOE_INCOME ;
_LP0 = _LP0 + (   -0.93002445933467 * _TEMP);

***  Effect: WOE_ACTIVE ;
_TEMP = WOE_ACTIVE ;
_LP0 = _LP0 + (   -1.02847239472468 * _TEMP);

***  Effect: WOE_AVGEXP ;
_TEMP = WOE_AVGEXP ;
_LP0 = _LP0 + (   -1.02429583669503 * _TEMP);

***  Effect: WOE_CUR_ADD ;
_TEMP = WOE_CUR_ADD ;
_LP0 = _LP0 + (   -0.83037702275877 * _TEMP);

***  Effect: WOE_DEPNDT ;
_TEMP = WOE_DEPNDT ;
_LP0 = _LP0 + (   -2.55978353395587 * _TEMP);

*** Naive Posterior Probabilities;
drop _MAXP _IY _P0 _P1;
_TEMP =    -2.24522798128165 + _LP0;
if (_TEMP < 0) then do;
   _TEMP = exp(_TEMP);
   _P0 = _TEMP / (1 + _TEMP);
end;
else _P0 = 1 / (1 + exp(-_TEMP));
_P1 = 1.0 - _P0;

SCORECARD3DR1:

*** Residuals;
if (_Y = .) then do;
   R_DEFAULT1_00 = .;
   R_DEFAULT0_00 = .;
end;
else do;
    label R_DEFAULT1_00 = 'Residual: DEFAULT=1.00' ;
    label R_DEFAULT0_00 = 'Residual: DEFAULT=0.00' ;
   R_DEFAULT1_00 = - _P0;
   R_DEFAULT0_00 = - _P1;
   select( _Y );
      when (0)  R_DEFAULT1_00 = R_DEFAULT1_00 + 1;
      when (1)  R_DEFAULT0_00 = R_DEFAULT0_00 + 1;
   end;
end;

*** Posterior Probabilities and Predicted Level;
label P_DEFAULT1_00 = 'Predicted: DEFAULT=1.00' ;
label P_DEFAULT0_00 = 'Predicted: DEFAULT=0.00' ;
P_DEFAULT1_00 = _P0;
_MAXP = _P0;
_IY = 1;
P_DEFAULT0_00 = _P1;
if (_P1 >  _MAXP + 1E-8) then do;
   _MAXP = _P1;
   _IY = 2;
end;
I_DEFAULT = SCORECARD3DRF[_IY];
U_DEFAULT = SCORECARD3DRU[_IY];

*************************************;
***** end scoring code for regression;
*************************************;
*------------------------------------------------------------*;
* generateScorepoints_note;
*------------------------------------------------------------*;
SCORECARD_POINTS = 0;

*------------------------------------------------------------*;
* Variable: ACTIVE;
*------------------------------------------------------------*;
if MISSING(ACTIVE) then do;
SCORECARD_POINTS = SCORECARD_POINTS + 27;
SCR_ACTIVE= 27;
end;
else if NOT MISSING(ACTIVE) AND ACTIVE < 2 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 114;
SCR_ACTIVE = 114;
end;
else if NOT MISSING(ACTIVE) and 2 <= ACTIVE AND ACTIVE < 7 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 27;
SCR_ACTIVE = 27;
end;
else if NOT MISSING(ACTIVE) and 7 <= ACTIVE AND ACTIVE < 11 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 20;
SCR_ACTIVE = 20;
end;
else if NOT MISSING(ACTIVE) and 11 <= ACTIVE AND ACTIVE < 12 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 51;
SCR_ACTIVE = 51;
end;
else if NOT MISSING(ACTIVE) and 12 <= ACTIVE then do;
SCORECARD_POINTS = SCORECARD_POINTS + 1;
SCR_ACTIVE = 1;
end;

*------------------------------------------------------------*;
* Variable: AGE;
*------------------------------------------------------------*;
if MISSING(AGE) then do;
SCORECARD_POINTS = SCORECARD_POINTS + 43;
SCR_AGE= 43;
end;
else if NOT MISSING(AGE) AND AGE < 27.75 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 43;
SCR_AGE = 43;
end;
else if NOT MISSING(AGE) and 27.75 <= AGE AND AGE < 29.83 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 6;
SCR_AGE = 6;
end;
else if NOT MISSING(AGE) and 29.83 <= AGE AND AGE < 32.33 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 65;
SCR_AGE = 65;
end;
else if NOT MISSING(AGE) and 32.33 <= AGE AND AGE < 44.92 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 13;
SCR_AGE = 13;
end;
else if NOT MISSING(AGE) and 44.92 <= AGE then do;
SCORECARD_POINTS = SCORECARD_POINTS + 26;
SCR_AGE = 26;
end;

*------------------------------------------------------------*;
* Variable: AVGEXP;
*------------------------------------------------------------*;
if MISSING(AVGEXP) then do;
SCORECARD_POINTS = SCORECARD_POINTS + 17;
SCR_AVGEXP= 17;
end;
else if NOT MISSING(AVGEXP) AND AVGEXP < 87.15 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 17;
SCR_AVGEXP = 17;
end;
else if NOT MISSING(AVGEXP) and 87.15 <= AVGEXP AND AVGEXP < 132.85 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 40;
SCR_AVGEXP = 40;
end;
else if NOT MISSING(AVGEXP) and 132.85 <= AVGEXP AND AVGEXP < 175.44 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 91;
SCR_AVGEXP = 91;
end;
else if NOT MISSING(AVGEXP) and 175.44 <= AVGEXP AND AVGEXP < 420.58 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 33;
SCR_AVGEXP = 33;
end;
else if NOT MISSING(AVGEXP) and 420.58 <= AVGEXP then do;
SCORECARD_POINTS = SCORECARD_POINTS + 3;
SCR_AVGEXP = 3;
end;

*------------------------------------------------------------*;
* Variable: CUR_ADD;
*------------------------------------------------------------*;
if MISSING(CUR_ADD) then do;
SCORECARD_POINTS = SCORECARD_POINTS + 14;
SCR_CUR_ADD= 14;
end;
else if NOT MISSING(CUR_ADD) AND CUR_ADD < 6 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 59;
SCR_CUR_ADD = 59;
end;
else if NOT MISSING(CUR_ADD) and 6 <= CUR_ADD AND CUR_ADD < 12 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 18;
SCR_CUR_ADD = 18;
end;
else if NOT MISSING(CUR_ADD) and 12 <= CUR_ADD AND CUR_ADD < 24 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 52;
SCR_CUR_ADD = 52;
end;
else if NOT MISSING(CUR_ADD) and 24 <= CUR_ADD AND CUR_ADD < 94 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 14;
SCR_CUR_ADD = 14;
end;
else if NOT MISSING(CUR_ADD) and 94 <= CUR_ADD then do;
SCORECARD_POINTS = SCORECARD_POINTS + 30;
SCR_CUR_ADD = 30;
end;

*------------------------------------------------------------*;
* Variable: DEPNDT;
*------------------------------------------------------------*;
if MISSING(DEPNDT) then do;
SCORECARD_POINTS = SCORECARD_POINTS + 15;
SCR_DEPNDT= 15;
end;
else if NOT MISSING(DEPNDT) AND DEPNDT < 1 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 15;
SCR_DEPNDT = 15;
end;
else if NOT MISSING(DEPNDT) and 1 <= DEPNDT AND DEPNDT < 2 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 24;
SCR_DEPNDT = 24;
end;
else if NOT MISSING(DEPNDT) and 2 <= DEPNDT AND DEPNDT < 3 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 40;
SCR_DEPNDT = 40;
end;
else if NOT MISSING(DEPNDT) and 3 <= DEPNDT AND DEPNDT < 4 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 19;
SCR_DEPNDT = 19;
end;
else if NOT MISSING(DEPNDT) and 4 <= DEPNDT then do;
SCORECARD_POINTS = SCORECARD_POINTS + 142;
SCR_DEPNDT = 142;
end;

*------------------------------------------------------------*;
* Variable: INCOME;
*------------------------------------------------------------*;
if MISSING(INCOME) then do;
SCORECARD_POINTS = SCORECARD_POINTS + 27;
SCR_INCOME= 27;
end;
else if NOT MISSING(INCOME) AND INCOME < 1.68 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 47;
SCR_INCOME = 47;
end;
else if NOT MISSING(INCOME) and 1.68 <= INCOME AND INCOME < 2.1 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 5;
SCR_INCOME = 5;
end;
else if NOT MISSING(INCOME) and 2.1 <= INCOME AND INCOME < 3.11 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 27;
SCR_INCOME = 27;
end;
else if NOT MISSING(INCOME) and 3.11 <= INCOME AND INCOME < 5.92 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 40;
SCR_INCOME = 40;
end;
else if NOT MISSING(INCOME) and 5.92 <= INCOME then do;
SCORECARD_POINTS = SCORECARD_POINTS + 1;
SCR_INCOME = 1;
end;
*;
* Assign SCORECARD_BIN values;
*;
if SCORECARD_POINTS < 54 then SCORECARD_BIN = 1;
else if SCORECARD_POINTS < 68 then SCORECARD_BIN = 2;
else if SCORECARD_POINTS < 82 then SCORECARD_BIN = 3;
else if SCORECARD_POINTS < 96 then SCORECARD_BIN = 4;
else if SCORECARD_POINTS < 110 then SCORECARD_BIN = 5;
else if SCORECARD_POINTS < 124 then SCORECARD_BIN = 6;
else if SCORECARD_POINTS < 138 then SCORECARD_BIN = 7;
else if SCORECARD_POINTS < 152 then SCORECARD_BIN = 8;
else if SCORECARD_POINTS < 166 then SCORECARD_BIN = 9;
else if SCORECARD_POINTS < 180 then SCORECARD_BIN = 10;
else if SCORECARD_POINTS < 194 then SCORECARD_BIN = 11;
else if SCORECARD_POINTS < 208 then SCORECARD_BIN = 12;
else if SCORECARD_POINTS < 222 then SCORECARD_BIN = 13;
else if SCORECARD_POINTS < 236 then SCORECARD_BIN = 14;
else if SCORECARD_POINTS < 250 then SCORECARD_BIN = 15;
else if SCORECARD_POINTS < 264 then SCORECARD_BIN = 16;
else if SCORECARD_POINTS < 278 then SCORECARD_BIN = 17;
else if SCORECARD_POINTS < 292 then SCORECARD_BIN = 18;
else if SCORECARD_POINTS < 306 then SCORECARD_BIN = 19;
else if SCORECARD_POINTS < 320 then SCORECARD_BIN = 20;
else if SCORECARD_POINTS < 334 then SCORECARD_BIN = 21;
else if SCORECARD_POINTS < 348 then SCORECARD_BIN = 22;
else if SCORECARD_POINTS < 362 then SCORECARD_BIN = 23;
else if SCORECARD_POINTS < 376 then SCORECARD_BIN = 24;
else SCORECARD_BIN = 25;
