SCORECARD_POINTS = 0;
 
*------------------------------------------------------------*;
* Variable: ACTIVE;
*------------------------------------------------------------*;
if MISSING(ACTIVE) then do;
SCORECARD_POINTS = SCORECARD_POINTS + 27;
SCR_ACTIVE= 27;
end;
else if NOT MISSING(ACTIVE) AND ACTIVE < 2 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 114;
SCR_ACTIVE = 114;
end;
else if NOT MISSING(ACTIVE) and 2 <= ACTIVE AND ACTIVE < 7 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 27;
SCR_ACTIVE = 27;
end;
else if NOT MISSING(ACTIVE) and 7 <= ACTIVE AND ACTIVE < 11 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 20;
SCR_ACTIVE = 20;
end;
else if NOT MISSING(ACTIVE) and 11 <= ACTIVE AND ACTIVE < 12 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 51;
SCR_ACTIVE = 51;
end;
else if NOT MISSING(ACTIVE) and 12 <= ACTIVE then do;
SCORECARD_POINTS = SCORECARD_POINTS + 1;
SCR_ACTIVE = 1;
end;
 
*------------------------------------------------------------*;
* Variable: AGE;
*------------------------------------------------------------*;
if MISSING(AGE) then do;
SCORECARD_POINTS = SCORECARD_POINTS + 43;
SCR_AGE= 43;
end;
else if NOT MISSING(AGE) AND AGE < 27.75 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 43;
SCR_AGE = 43;
end;
else if NOT MISSING(AGE) and 27.75 <= AGE AND AGE < 29.83 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 6;
SCR_AGE = 6;
end;
else if NOT MISSING(AGE) and 29.83 <= AGE AND AGE < 32.33 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 65;
SCR_AGE = 65;
end;
else if NOT MISSING(AGE) and 32.33 <= AGE AND AGE < 44.92 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 13;
SCR_AGE = 13;
end;
else if NOT MISSING(AGE) and 44.92 <= AGE then do;
SCORECARD_POINTS = SCORECARD_POINTS + 26;
SCR_AGE = 26;
end;
 
*------------------------------------------------------------*;
* Variable: AVGEXP;
*------------------------------------------------------------*;
if MISSING(AVGEXP) then do;
SCORECARD_POINTS = SCORECARD_POINTS + 17;
SCR_AVGEXP= 17;
end;
else if NOT MISSING(AVGEXP) AND AVGEXP < 87.15 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 17;
SCR_AVGEXP = 17;
end;
else if NOT MISSING(AVGEXP) and 87.15 <= AVGEXP AND AVGEXP < 132.85 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 40;
SCR_AVGEXP = 40;
end;
else if NOT MISSING(AVGEXP) and 132.85 <= AVGEXP AND AVGEXP < 175.44 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 91;
SCR_AVGEXP = 91;
end;
else if NOT MISSING(AVGEXP) and 175.44 <= AVGEXP AND AVGEXP < 420.58 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 33;
SCR_AVGEXP = 33;
end;
else if NOT MISSING(AVGEXP) and 420.58 <= AVGEXP then do;
SCORECARD_POINTS = SCORECARD_POINTS + 3;
SCR_AVGEXP = 3;
end;
 
*------------------------------------------------------------*;
* Variable: CUR_ADD;
*------------------------------------------------------------*;
if MISSING(CUR_ADD) then do;
SCORECARD_POINTS = SCORECARD_POINTS + 14;
SCR_CUR_ADD= 14;
end;
else if NOT MISSING(CUR_ADD) AND CUR_ADD < 6 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 59;
SCR_CUR_ADD = 59;
end;
else if NOT MISSING(CUR_ADD) and 6 <= CUR_ADD AND CUR_ADD < 12 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 18;
SCR_CUR_ADD = 18;
end;
else if NOT MISSING(CUR_ADD) and 12 <= CUR_ADD AND CUR_ADD < 24 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 52;
SCR_CUR_ADD = 52;
end;
else if NOT MISSING(CUR_ADD) and 24 <= CUR_ADD AND CUR_ADD < 94 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 14;
SCR_CUR_ADD = 14;
end;
else if NOT MISSING(CUR_ADD) and 94 <= CUR_ADD then do;
SCORECARD_POINTS = SCORECARD_POINTS + 30;
SCR_CUR_ADD = 30;
end;
 
*------------------------------------------------------------*;
* Variable: DEPNDT;
*------------------------------------------------------------*;
if MISSING(DEPNDT) then do;
SCORECARD_POINTS = SCORECARD_POINTS + 15;
SCR_DEPNDT= 15;
end;
else if NOT MISSING(DEPNDT) AND DEPNDT < 1 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 15;
SCR_DEPNDT = 15;
end;
else if NOT MISSING(DEPNDT) and 1 <= DEPNDT AND DEPNDT < 2 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 24;
SCR_DEPNDT = 24;
end;
else if NOT MISSING(DEPNDT) and 2 <= DEPNDT AND DEPNDT < 3 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 40;
SCR_DEPNDT = 40;
end;
else if NOT MISSING(DEPNDT) and 3 <= DEPNDT AND DEPNDT < 4 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 19;
SCR_DEPNDT = 19;
end;
else if NOT MISSING(DEPNDT) and 4 <= DEPNDT then do;
SCORECARD_POINTS = SCORECARD_POINTS + 142;
SCR_DEPNDT = 142;
end;
 
*------------------------------------------------------------*;
* Variable: INCOME;
*------------------------------------------------------------*;
if MISSING(INCOME) then do;
SCORECARD_POINTS = SCORECARD_POINTS + 27;
SCR_INCOME= 27;
end;
else if NOT MISSING(INCOME) AND INCOME < 1.68 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 47;
SCR_INCOME = 47;
end;
else if NOT MISSING(INCOME) and 1.68 <= INCOME AND INCOME < 2.1 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 5;
SCR_INCOME = 5;
end;
else if NOT MISSING(INCOME) and 2.1 <= INCOME AND INCOME < 3.11 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 27;
SCR_INCOME = 27;
end;
else if NOT MISSING(INCOME) and 3.11 <= INCOME AND INCOME < 5.92 then do;
SCORECARD_POINTS = SCORECARD_POINTS + 40;
SCR_INCOME = 40;
end;
else if NOT MISSING(INCOME) and 5.92 <= INCOME then do;
SCORECARD_POINTS = SCORECARD_POINTS + 1;
SCR_INCOME = 1;
end;
