-- ----------------------------------------------------
-- CREACION BASE DE DATOS DW
-- ----------------------------------------------------

CREATE DATABASE DW_VTIGERCRM521;
USE DW_VTIGERCRM521;

-- ----------------------------------------------------
-- CREACION TABLAS DW
-- ----------------------------------------------------

-- HECHOS
DROP TABLE FACT_SALESORDERINVENTORY;
CREATE TABLE FACT_SALESORDERINVENTORY (
    SALESORDERINVENTORY_ID INT(15) NOT NULL,
	SALESORDER_ID INT(15) NOT NULL,
	CONTACT_ID INT(11) NOT NULL,
	DATE_ID DATE NOT NULL,
	PRODUCT_ID INT(11) NOT NULL,
	USER_ID INT(11) NOT NULL,
	NETPRICE_AMT DECIMAL(15,2),
	PRIMARY KEY (SALESORDERINVENTORY_ID)
);

-- ERROR HECHOS
DROP TABLE ERR_FACT_SALESORDERINVENTORY;
CREATE TABLE ERR_FACT_SALESORDERINVENTORY (
    SALESORDERINVENTORY_ID INT(15) NOT NULL,
	SALESORDER_ID INT(15) NOT NULL,
	CONTACT_ID INT(11) NOT NULL,
	DATE_ID DATE NOT NULL,
	PRODUCT_ID INT(11) NOT NULL,
	USER_ID INT(11) NOT NULL,
	NETPRICE_AMT DECIMAL(15,2),
	ERR_DESC VARCHAR(200)
);


-- DIMENSIONES
DROP TABLE DIM_DATE;
 CREATE TABLE DIM_DATE
   (DATE_ID DATE NOT NULL, 
	DATE_DESC VARCHAR(19) NOT NULL, 
	WEEK_ID INT(6), 
	WEEK_DESC VARCHAR(20), 
	MONTH_ID DATE NOT NULL, 
	MONTH_DESC VARCHAR(20), 
	YEAR_ID VARCHAR(4), 
	YEAR_DESC VARCHAR(9),
	PRIMARY KEY (DATE_ID)
   );
 
DROP TABLE DIM_SALESORDER; 
CREATE TABLE DIM_SALESORDER (
	SALESORDER_ID INT(15) NOT NULL,
	SALESORDER_NO VARCHAR(30) NOT NULL,
	SALESORDER_DESC VARCHAR(100) NOT NULL,
	CARRIER_ID VARCHAR(50),
	CARRIER_DESC VARCHAR(200),
	PRIMARY KEY (SALESORDER_ID)
);

DROP TABLE DIM_CONTACTS; 
CREATE TABLE DIM_CONTACTS (
	CONTACT_ID INT(11) NOT NULL,
	CONTACT_NO VARCHAR(30) NOT NULL,
	CONTACT_DESC VARCHAR(100) NOT NULL,
	BIRTHDAY DATE,
	AGE INT(4),
	FAMILYSIZE INT(4),
	JOBSTARDATE DATE,
	YEAREXPERIENCE INT(4),
	ANNUALINCOME INT(6),
	EDUCATIONLEVEL_ID INT(1),
	EDUCATIONLEVEL_DESC VARCHAR(30),
	PRIMARY KEY (CONTACT_ID)	
);

DROP TABLE DIM_PRODUCTS;
CREATE TABLE DIM_PRODUCTS (
	PRODUCT_ID INT(11) NOT NULL,
	PRODUCT_NO VARCHAR(30) NOT NULL,
	PRODUCT_DESC VARCHAR(50) NOT NULL,
	PRODUCTCATEGORY_ID VARCHAR(30),
	PRODUCTCATEGORY_DESC VARCHAR(100),
	PRIMARY KEY (PRODUCT_ID)		
);

DROP TABLE DIM_USERS;
CREATE TABLE DIM_USERS (
	USER_ID INT(11) NOT NULL,
	USER_DESC VARCHAR(100) NOT NULL,
	GROUP_FLAG VARCHAR(1),
	ROLE_ID VARCHAR(50),
	ROLE_DESC VARCHAR(50),	
	DEPTH INT(3),
	PRIMARY KEY (USER_ID)			
);
