-- ----------------------------------------------------
-- EXPLOTACION CUBO: OLAP
-- ----------------------------------------------------

SELECT CON.CONTACT_ID,CON.CONTACT_DESC, CON.EDUCATIONLEVEL_ID, CON.EDUCATIONLEVEL_DESC,
		 DAT.DATE_ID,DAT.DATE_DESC,WEEK_ID,WEEK_DESC,MONTH_ID,MONTH_DESC,YEAR_ID,YEAR_DESC,
		 PRO.PRODUCT_ID,PRO.PRODUCT_DESC,PRO.PRODUCTCATEGORY_ID,PRODUCTCATEGORY_DESC,
		 SAL.SALESORDER_ID,SAL.SALESORDER_DESC,SAL.CARRIER_ID,SAL.CARRIER_DESC,
		 USU.USER_ID,USU.USER_DESC,USU.ROLE_ID,USU.ROLE_DESC,
		 FACT.NETPRICE_AMT
	FROM FACT_SALESORDERINVENTORY FACT
	JOIN DIM_CONTACTS CON ON CON.CONTACT_ID=FACT.CONTACT_ID
	JOIN DIM_DATE DAT ON DAT.DATE_ID=FACT.DATE_ID
	JOIN DIM_PRODUCTS PRO ON PRO.PRODUCT_ID=FACT.PRODUCT_ID
	JOIN DIM_SALESORDER SAL ON SAL.SALESORDER_ID=FACT.SALESORDER_ID
	JOIN DIM_USERS USU ON USU.USER_ID=FACT.USER_ID;


