SELECT FACT.CONTACT_ID, 
       CON.AGE,
	    CON.FAMILYSIZE,
       CON.YEAREXPERIENCE,
	    CON.ANNUALINCOME,
	    CON.EDUCATIONLEVEL_ID,
	SUM(
		CASE WHEN product_no='PRO11' THEN NETPRICE_AMT
			 ELSE 0
		END) NETPRICE_PRO11_AMT,
	SUM(
		CASE WHEN product_no='PRO12' THEN NETPRICE_AMT
			 ELSE 0
		END) NETPRICE_PRO12_AMT,
	SUM(
		CASE WHEN product_no='PRO13' THEN NETPRICE_AMT
			 ELSE 0
		END) NETPRICE_PRO13_AMT,
	SUM(
		CASE WHEN product_no='PRO14' THEN NETPRICE_AMT
			 ELSE 0
		END) NETPRICE_PRO14_AMT,
	SUM(
		CASE WHEN product_no='PRO15' THEN NETPRICE_AMT
			 ELSE 0
		END) NETPRICE_PRO15_AMT,
	SUM(
		CASE WHEN product_no='PRO16' THEN NETPRICE_AMT
			 ELSE 0
		END) NETPRICE_PRO16_AMT,
	SUM(
		CASE WHEN product_no='PRO17' THEN NETPRICE_AMT
			 ELSE 0
		END) NETPRICE_PRO17_AMT
	FROM FACT_SALESORDERINVENTORY FACT
	JOIN DIM_CONTACTS CON ON CON.CONTACT_ID=FACT.CONTACT_ID
	JOIN DIM_PRODUCTS PRO ON PRO.PRODUCT_ID=FACT.PRODUCT_ID
GROUP BY 1,2,3,4,5,6