*------------------------------------------------------------*;
* Generando clases para las variables de intervalo;
*------------------------------------------------------------*;
if ACTIVE eq . then BIN_ACTIVE= .;
else do;
if ACTIVE < 0 then BIN_ACTIVE=1;
else if ACTIVE < 1 then BIN_ACTIVE=2;
else if ACTIVE < 2 then BIN_ACTIVE=3;
else if ACTIVE < 3 then BIN_ACTIVE=4;
else if ACTIVE < 4 then BIN_ACTIVE=5;
else if ACTIVE < 5 then BIN_ACTIVE=6;
else if ACTIVE < 6 then BIN_ACTIVE=7;
else if ACTIVE < 7 then BIN_ACTIVE=8;
else if ACTIVE < 9 then BIN_ACTIVE=9;
else if ACTIVE < 11 then BIN_ACTIVE=10;
else if ACTIVE < 12 then BIN_ACTIVE=11;
else if ACTIVE < 14 then BIN_ACTIVE=12;
else if ACTIVE < 16 then BIN_ACTIVE=13;
else if ACTIVE < 18 then BIN_ACTIVE=14;
else if ACTIVE >= 18 then BIN_ACTIVE=15;
end;
if AGE eq . then BIN_AGE= .;
else do;
if AGE < 21.17 then BIN_AGE=1;
else if AGE < 22.17 then BIN_AGE=2;
else if AGE < 23.33 then BIN_AGE=3;
else if AGE < 24.5 then BIN_AGE=4;
else if AGE < 25.17 then BIN_AGE=5;
else if AGE < 26.25 then BIN_AGE=6;
else if AGE < 27.75 then BIN_AGE=7;
else if AGE < 28.42 then BIN_AGE=8;
else if AGE < 29.83 then BIN_AGE=9;
else if AGE < 31.33 then BIN_AGE=10;
else if AGE < 32.33 then BIN_AGE=11;
else if AGE < 34 then BIN_AGE=12;
else if AGE < 35.25 then BIN_AGE=13;
else if AGE < 37.08 then BIN_AGE=14;
else if AGE < 39.33 then BIN_AGE=15;
else if AGE < 41.67 then BIN_AGE=16;
else if AGE < 44.92 then BIN_AGE=17;
else if AGE < 48.25 then BIN_AGE=18;
else if AGE < 52.42 then BIN_AGE=19;
else if AGE >= 52.42 then BIN_AGE=20;
end;
if AVGEXP eq . then BIN_AVGEXP= .;
else do;
if AVGEXP < 7.42 then BIN_AVGEXP=1;
else if AVGEXP < 22.36 then BIN_AVGEXP=2;
else if AVGEXP < 43.74 then BIN_AVGEXP=3;
else if AVGEXP < 59.12 then BIN_AVGEXP=4;
else if AVGEXP < 73.18 then BIN_AVGEXP=5;
else if AVGEXP < 87.15 then BIN_AVGEXP=6;
else if AVGEXP < 98.35 then BIN_AVGEXP=7;
else if AVGEXP < 116.35 then BIN_AVGEXP=8;
else if AVGEXP < 132.85 then BIN_AVGEXP=9;
else if AVGEXP < 153.74 then BIN_AVGEXP=10;
else if AVGEXP < 175.44 then BIN_AVGEXP=11;
else if AVGEXP < 198.55 then BIN_AVGEXP=12;
else if AVGEXP < 220.79 then BIN_AVGEXP=13;
else if AVGEXP < 273.49 then BIN_AVGEXP=14;
else if AVGEXP < 324.03 then BIN_AVGEXP=15;
else if AVGEXP < 362.75 then BIN_AVGEXP=16;
else if AVGEXP < 420.58 then BIN_AVGEXP=17;
else if AVGEXP < 476.32 then BIN_AVGEXP=18;
else if AVGEXP < 675.77 then BIN_AVGEXP=19;
else if AVGEXP >= 675.77 then BIN_AVGEXP=20;
end;
if CUR_ADD eq . then BIN_CUR_ADD= .;
else do;
if CUR_ADD < 3 then BIN_CUR_ADD=1;
else if CUR_ADD < 6 then BIN_CUR_ADD=2;
else if CUR_ADD < 7 then BIN_CUR_ADD=3;
else if CUR_ADD < 10 then BIN_CUR_ADD=4;
else if CUR_ADD < 12 then BIN_CUR_ADD=5;
else if CUR_ADD < 15 then BIN_CUR_ADD=6;
else if CUR_ADD < 20 then BIN_CUR_ADD=7;
else if CUR_ADD < 24 then BIN_CUR_ADD=8;
else if CUR_ADD < 26 then BIN_CUR_ADD=9;
else if CUR_ADD < 32 then BIN_CUR_ADD=10;
else if CUR_ADD < 39 then BIN_CUR_ADD=11;
else if CUR_ADD < 49 then BIN_CUR_ADD=12;
else if CUR_ADD < 57 then BIN_CUR_ADD=13;
else if CUR_ADD < 72 then BIN_CUR_ADD=14;
else if CUR_ADD < 94 then BIN_CUR_ADD=15;
else if CUR_ADD < 120 then BIN_CUR_ADD=16;
else if CUR_ADD < 147 then BIN_CUR_ADD=17;
else if CUR_ADD < 192 then BIN_CUR_ADD=18;
else if CUR_ADD >= 192 then BIN_CUR_ADD=19;
end;
if DEPNDT eq . then BIN_DEPNDT= .;
else do;
if DEPNDT < 0 then BIN_DEPNDT=1;
else if DEPNDT < 1 then BIN_DEPNDT=2;
else if DEPNDT < 2 then BIN_DEPNDT=3;
else if DEPNDT < 3 then BIN_DEPNDT=4;
else if DEPNDT < 4 then BIN_DEPNDT=5;
else if DEPNDT >= 4 then BIN_DEPNDT=6;
end;
if EXP_INC eq . then BIN_EXP_INC= .;
else do;
if EXP_INC < 0 then BIN_EXP_INC=1;
else if EXP_INC < 0.01 then BIN_EXP_INC=2;
else if EXP_INC < 0.02 then BIN_EXP_INC=3;
else if EXP_INC < 0.03 then BIN_EXP_INC=4;
else if EXP_INC < 0.04 then BIN_EXP_INC=5;
else if EXP_INC < 0.05 then BIN_EXP_INC=6;
else if EXP_INC < 0.06 then BIN_EXP_INC=7;
else if EXP_INC < 0.07 then BIN_EXP_INC=8;
else if EXP_INC < 0.08 then BIN_EXP_INC=9;
else if EXP_INC < 0.09 then BIN_EXP_INC=10;
else if EXP_INC < 0.1 then BIN_EXP_INC=11;
else if EXP_INC < 0.11 then BIN_EXP_INC=12;
else if EXP_INC < 0.14 then BIN_EXP_INC=13;
else if EXP_INC < 0.17 then BIN_EXP_INC=14;
else if EXP_INC < 0.19 then BIN_EXP_INC=15;
else if EXP_INC < 0.27 then BIN_EXP_INC=16;
else if EXP_INC >= 0.27 then BIN_EXP_INC=17;
end;
if INCOME eq . then BIN_INCOME= .;
else do;
if INCOME < 1.68 then BIN_INCOME=1;
else if INCOME < 1.92 then BIN_INCOME=2;
else if INCOME < 2.1 then BIN_INCOME=3;
else if INCOME < 2.25 then BIN_INCOME=4;
else if INCOME < 2.4 then BIN_INCOME=5;
else if INCOME < 2.5 then BIN_INCOME=6;
else if INCOME < 2.6 then BIN_INCOME=7;
else if INCOME < 2.7 then BIN_INCOME=8;
else if INCOME < 2.83 then BIN_INCOME=9;
else if INCOME < 3 then BIN_INCOME=10;
else if INCOME < 3.11 then BIN_INCOME=11;
else if INCOME < 3.35 then BIN_INCOME=12;
else if INCOME < 3.58 then BIN_INCOME=13;
else if INCOME < 3.9 then BIN_INCOME=14;
else if INCOME < 4.3 then BIN_INCOME=15;
else if INCOME < 4.8 then BIN_INCOME=16;
else if INCOME < 5.1 then BIN_INCOME=17;
else if INCOME < 5.92 then BIN_INCOME=18;
else if INCOME < 7.35 then BIN_INCOME=19;
else if INCOME >= 7.35 then BIN_INCOME=20;
end;
if INC_PER eq . then BIN_INC_PER= .;
else do;
if INC_PER < 0.75 then BIN_INC_PER=1;
else if INC_PER < 0.92 then BIN_INC_PER=2;
else if INC_PER < 1.05 then BIN_INC_PER=3;
else if INC_PER < 1.2 then BIN_INC_PER=4;
else if INC_PER < 1.28 then BIN_INC_PER=5;
else if INC_PER < 1.42 then BIN_INC_PER=6;
else if INC_PER < 1.56 then BIN_INC_PER=7;
else if INC_PER < 1.68 then BIN_INC_PER=8;
else if INC_PER < 1.86 then BIN_INC_PER=9;
else if INC_PER < 2.05 then BIN_INC_PER=10;
else if INC_PER < 2.2 then BIN_INC_PER=11;
else if INC_PER < 2.36 then BIN_INC_PER=12;
else if INC_PER < 2.5 then BIN_INC_PER=13;
else if INC_PER < 2.6 then BIN_INC_PER=14;
else if INC_PER < 2.8 then BIN_INC_PER=15;
else if INC_PER < 3 then BIN_INC_PER=16;
else if INC_PER < 3.25 then BIN_INC_PER=17;
else if INC_PER < 3.75 then BIN_INC_PER=18;
else if INC_PER < 5 then BIN_INC_PER=19;
else if INC_PER >= 5 then BIN_INC_PER=20;
end;
if MAJOR eq . then BIN_MAJOR= .;
else do;
if MAJOR < 0 then BIN_MAJOR=1;
else if MAJOR < 1 then BIN_MAJOR=2;
else if MAJOR >= 1 then BIN_MAJOR=3;
end;
drop
ACTIVE
AGE
AVGEXP
CUR_ADD
DEPNDT
EXP_INC
INCOME
INC_PER
MAJOR
;
